version: 0.2
phases:
  build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - echo $repoUri
      - docker build -t=${repoUri}/buildimage:latest .
      - docker push ${repoUri}/buildimage:latest